#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     FrontRight,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     BackRight,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     FrontLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     BackLeft,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     LeftSlide,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     RightSlide,    tmotorTetrix, PIDControl, encoder)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//Constants
#include "constants.h"

//Useful functions
#include "common.h"

//Music player
#include "Player.h"

string programs[] = { "Left IR", "Left Non-IR", "Right IR", "Right Non-IR" };

task main() {
	bDisplayDiagnostics = false; //Disable screen diagnostics until Autonomous is set up

	//Initialize
	initialize();

	int prog = 0; //Autonomous program

	//Prompt for autonomous program
	nxtDisplayCenteredTextLine(3, "Select program:");
	nxtDisplayCenteredTextLine(5, "%s", programs[prog]);
	while(nNxtButtonPressed != 3) { //Wait for press
		wait10Msec(20);

		if(nNxtButtonPressed == 2 && prog > 0) { //Decrement the program
			prog--;
			nxtDisplayCenteredTextLine(5, "%s", programs[prog]); //Display its name
		}
		else if(nNxtButtonPressed == 1 && prog < sizeof(programs)/sizeof(programs[0]) - 1) { //Increment the program
			prog++;
			nxtDisplayCenteredTextLine(5, "%s", programs[prog]);
		}
	}
	while(nNxtButtonPressed == 3){ //Wait for unpress

		//Add a delay
	int delay = 0;
	nxtDisplayCenteredTextLine(3, "Delay:");
	nxtDisplayCenteredTextLine(5, "%d", delay);
	while(nNxtButtonPressed != 3) { //Wait for press
		wait10Msec(20);

		if(nNxtButtonPressed == 2 && delay > 0) { //Decrement the delay
			delay -= 2;
			nxtDisplayCenteredTextLine(5, "%d", delay);
		}
		else if(nNxtButtonPressed == 1 && delay < 30) { //Increment the delay
			delay += 2;
			nxtDisplayCenteredTextLine(5, "%d", delay);
		}
	}
	while(nNxtButtonPressed == 3); //Wait for unpress

	bDisplayDiagnostics = true; //Enable screen diagnostics for match

	//Go time!
	waitForStart();

	//Play the Imperial March
	setSong("ImperialMarch.nms");
	play();

	wait10Msec(delay * 100);

	}
}
