#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S3,     IR_left,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     IR_right,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     FrontRight,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     BackRight,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     FrontLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     BackLeft,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     LeftSlide,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     RightSlide,    tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S2_C2_1,    zipties,              tServoContinuousRotation)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//Constants
#include "constants.h"

//Useful functions
#include "common.h"

//Music player
#include "Player.h"

string programs[] = { "Left IR", "Left Non-IR", "Right IR", "Right Non-IR" };

void execute(bool ramp, bool def, bool kick, bool center, int roll) {			//I feel like this should be outside of task main()

//	float xPos = 0;
//	float yPos = 0;
//	float angle = 0;

	//***NOTE*** All IR values in various branches have not been calibrated. They might be (for example) 3, 4, or 5 instead of 4, 5, or 6.
		if (ramp == true) {			//If starting from ramp
		drive(18000);
		
			if (def == true) {
				//run defense program for ramp beginning

			}
			else {

				if (kick == true) {
					//run kickstand method for ramp start	

					if (SensorValue[IR_left] == 7 && SensorValue[IR_right] == 0) { //center goal is facing the box
						//knock over kickstand and return to a common point
						turn(45);
						drive(4000);
						turn(135);
						drive(3000);
						//moveTo(angle, xPos, yPos, 0, 800);
					}

					if (SensorValue[IR_left] == 5 && SensorValue[IR_right] == 6) { //center goal is facing at a 45 degree angle between the box and side of the ramp
						//knock over kickstand and return to a common point
						turn(45);
						drive(4000);
						turn(135);
						drive(3000);
						//moveTo(angle, xPos, yPos, 0, 800);
					}

					if (SensorValue[IR_left] == 5 && SensorValue[IR_right] == 5) { //center goal is facing toward the side of the ramp
						turn(45);
						drive(4000);
						turn(135);
						drive(3000);
						//moveTo(angle, xPos, yPos, 0, 800);
				  }
				}
			}

				if (center == true) {//If scoring in center goal
					//locate center goal and score in it
					if (SensorValue[IR_left] == 7 && SensorValue[IR_right] == 0) { //center goal is facing toward the box
						turn(45);
						drive(10000);
						turn(-45);
						liftScore(CENTER_GOAL);

					}
					if (SensorValue[IR_left] == 6 && SensorValue[IR_right] == 5) { //center goal is facing at a 45 degree angle between the box and side of the ramp
						//knock over kickstand and return to a common point
						turn(45);
						drive(10000);
						turn(30);
						liftScore(CENTER_GOAL);
					}
					if (SensorValue[IR_left] == 5 && SensorValue[IR_right] == 5) { //center goal is facing toward the side of the ramp
						turn(45);
						drive(10000);
						turn(80);
						liftScore(CENTER_GOAL);
					}
					//reset robot to home position
				}
				if (center == false) {		//If not scoring in center goal

					//(0 = no rolling goals, 1 = medium goal only, 2 = high goal only, 3 = both goals)
					if (roll == 0) {
					//do nothing
					}

					if (roll == 1) {
					//score in medium goal and bring it back (bring it back can be a common.h method) to parking zone
						turn(20);
						drive(7000);
						liftScore(MEDIUM_GOAL);
						turn(150);
						drive(10000);
					}
					if (roll == 2) {
					//score in tallest goal and bring it back
						turn(30);
						drive(2000);
						turn(-60);
						drive(5000);
						liftScore(HIGH_GOAL);
						turn(90);
						drive(12000);
					}
					if (roll == 3) {
					//score in medium and tallest then bring back the tallest goal
						turn(30);
						drive(2000);
						turn(-60);
						drive(5000);
						liftScore(HIGH_GOAL);
						turn(60);
						liftScore(MEDIUM_GOAL);
						turn(140);
						drive(10000);
					}
				}

		if (ramp == false) {
			drive(12000);
			turn(45);
		
			if (def == true) {
				//run defense program for floor beginning
			}
			if (kick == true) {

					if (SensorValue[IR_left] == 7 && SensorValue[IR_right] == 0) { //center goal is facing the box
						//knock over kickstand and return to a common point
						turn(45);
						drive(2000);
						turn(135);
						drive(3000);
						//moveTo(angle, xPos, yPos, 0, 800);
					}

					if (SensorValue[IR_left] == 5 && SensorValue[IR_right] == 6) { //center goal is facing at a 45 degree angle between the box and side of the ramp
						//knock over kickstand and return to a common point
						turn(45);
						drive(2000);
						turn(135);
						drive(3000);
						//moveTo(angle, xPos, yPos, 0, 800);
					}

					if (SensorValue[IR_left] == 5 && SensorValue[IR_right] == 5) { //center goal is facing toward the side of the ramp
						turn(45);
						drive(2000);
						turn(135);
						drive(3000);
						//moveTo(angle, xPos, yPos, 0, 800);
				  }
				}

				if (center == true) {
					//locate center goal and score in it
					
					if (SensorValue[IR_left] == 7 && SensorValue[IR_right] == 0) { //center goal is facing toward the box
						turn(45);
						drive(10000);
						turn(-45);
						liftScore(CENTER_GOAL);

					}
					if (SensorValue[IR_left] == 6 && SensorValue[IR_right] == 5) { //center goal is facing at a 45 degree angle between the box and side of the ramp
						//knock over kickstand and return to a common point
						turn(45);
						drive(10000);
						turn(30);
						liftScore(CENTER_GOAL);
					}
					if (SensorValue[IR_left] == 5 && SensorValue[IR_right] == 5) { //center goal is facing toward the side of the ramp
						turn(45);
						drive(10000);
						turn(80);
						liftScore(CENTER_GOAL);
					}
					//reset robot to home position
				}
				if (center == false) {		//If not scoring in center goal

					//(0 = no rolling goals, 1 = medium goal only, 2 = high goal only, 3 = both goals)
					if (roll == 0) {
					//do nothing
					}

					if (roll == 1) {
					//score in medium goal and bring it back (bring it back can be a common.h method) to parking zone
						turn(20);
						drive(7000);
						liftScore(MEDIUM_GOAL);
						turn(150);
						drive(10000);
					}
					if (roll == 2) {
					//score in tallest goal and bring it back
						turn(30);
						drive(2000);
						turn(-60);
						drive(5000);
						liftScore(HIGH_GOAL);
						turn(90);
						drive(12000);
					}
					if (roll == 3) {
					//score in medium and tallest then bring back the tallest goal
						turn(30);
						drive(2000);
						turn(-60);
						drive(5000);
						liftScore(HIGH_GOAL);
						turn(60);
						liftScore(MEDIUM_GOAL);
						turn(140);
						drive(10000);
					}
				}
			}
		}
	}

task main() {
	bDisplayDiagnostics = false; //Disable screen diagnostics until Autonomous is set up

	//Initialize
	initialize();

	int prog = 0; //Autonomous program

	//Prompt for autonomous program
	nxtDisplayCenteredTextLine(3, "Select program:");
	nxtDisplayCenteredTextLine(5, "%s", programs[prog]);
	while(nNxtButtonPressed != 3) { //Wait for press
		wait10Msec(20);

		if(nNxtButtonPressed == 2 && prog > 0) { //Decrement the program
			prog--;
			nxtDisplayCenteredTextLine(5, "%s", programs[prog]); //Display its name
		}
		else if(nNxtButtonPressed == 1 && prog < sizeof(programs)/sizeof(programs[0]) - 1) { //Increment the program
			prog++;
			nxtDisplayCenteredTextLine(5, "%s", programs[prog]);
		}
	}
	while(nNxtButtonPressed == 3){ //Wait for unpress

		//Add a delay
	int delay = 0;
	nxtDisplayCenteredTextLine(3, "Delay:");
	nxtDisplayCenteredTextLine(5, "%d", delay);
	while(nNxtButtonPressed != 3) { //Wait for press
		wait10Msec(20);

		if(nNxtButtonPressed == 2 && delay > 0) { //Decrement the delay
			delay -= 2;
			nxtDisplayCenteredTextLine(5, "%d", delay);
		}
		else if(nNxtButtonPressed == 1 && delay < 30) { //Increment the delay
			delay += 2;
			nxtDisplayCenteredTextLine(5, "%d", delay);
		}
	}
	while(nNxtButtonPressed == 3); //Wait for unpress

	bDisplayDiagnostics = true; //Enable screen diagnostics for match

	//Go time!
	waitForStart();

	//Play the Imperial March
	//setSong("ImperialMarch.nms");
	//play();

	wait10Msec(delay * 100);

	}

	//SensorValue[IR]

	execute(RAMP, DEF, KICK, CENTER, ROLLING);

	//writeDebugStream("IR:\t%d\n", SensorValue[IR]);

}
