#pragma config(Hubs, S1, HTMotor, HTMotor, none, none)
#pragma config(Sensor, S1, , sensorI2CMuxController)
#pragma config(Motor, mtr_S1_C1_1, FrontLeft, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor, mtr_S1_C1_2, FrontRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor, mtr_S1_C2_1, BackLeft, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor, mtr_S1_C2_2, BackRight, tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "constants.h"

int targetMotorSpeed(float total, float current, float offset) {
#ifdef NONLINEARTARGET
	return 100 * (1 - sqrt((1 / total) * (current - offset)));
#else
	return 100;
#endif
}

void turnLeft(int encoderCount) {
	//TODO
}

void turnRight(int encoderCount) {
	//TODO
}

void forward(int encoderCount) {
	//TODO
}

void backward(int encoderCount) {
	//TODO
}

void right(int encoderCount) {
	//TODO
}

void left(int encoderCount) {
	//TODO
}
