//Flags
#define NONLINEARTARGET

//Scaling
#define DRIVE_HIGH 100
#define DRIVE_LOW 30
#define ARM_HIGH 100
#define ARM_LOW 30
#define HAND_HIGH 50

//Robot Constants
#define ARM_SHOULDER_TOP 28000
#define ARM_SHOULDER_BOTTOM 0
#define HAND_MAX 1400
#define HAND_MIN 0

//Presets
#define ENCODER_PRECISION 60
#define ARM_SHOULDER_PICKUP 26600
#define ARM_ELBOW_PICKUP 1800
#define ARM_SHOULDER_HANG 10000
#define ARM_ELBOW_HANG 2000

//Testing
#define TEST_ENCODER 4800
