//Flag for whether to use tank drive or not
//#define TANKDRIVE
//#define NONLINEARTARGET

//Scaling
#define JOYSTICKHIGH 100
#define JOYSTICKLOW 30
#define SHOULDERHIGH 55
#define SHOULDERLOW 20
#define SHOULDERDOWNHIGH 2
#define SHOULDERDOWNLOW 1
#define ARMHIGH 35
#define ARMLOW 15
#define ARMDOWNHIGH 2
#define ARMDOWNLOW 1
#define HANDHIGH 100
//Robot Constants
#define SHOULDERTOP 2200
#define SHOULDERBOTTOM 0
#define SHOULDERUPRIGHT 2100
#define ARMTOP 800
#define ARMBOTTOM -800
#define ARMUPRIGHT 64
#define HANDMAX 300
#define HANDMIN 0
//Field Constants
#define RINGPEGSHOULDER 0
#define RINGPEGARM 240
#define BOTTOMPEGARM 280
#define BOTTOMPEGSHOULDER 0
#define MIDDLEPEGSHOULDER 1500
#define MIDDLEPEGARM 300
#define TOPPEGSHOULDER 2200
#define TOPPEGARM 540

//Autonomous
#define STARTFORWARD 4800
#define SENSORTURN 200
#define TURN 2800
#define SIDEWAYS 1800
#define CENTERFORWARD 3000
#define PLACEFORWARD 200
#define BACKWARDS 1440
#define TURNTORINGS 1200
#define FORWARDTORINGS 2400

//Testing
#define ENCODERTEST 4800
