#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IR,             sensorAnalog)
#pragma config(Motor,  mtr_S1_C1_1,     RightForward,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     BackSideways,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     FrontSideways, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     LeftForward,   tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main() {
	while(true) {
		if(joy1Btn(1))
			motor[LeftForward] = 100;
		else
			motor[LeftForward] = 0;
		if(joy1Btn(2))
			motor[RightForward] = 100;
		else
			motor[RightForward] = 0;
		if(joy1Btn(3))
			motor[BackSideways] = 100;
		else
			motor[BackSideways] = 0;
		if(joy1Btn(4))
			motor[FrontSideways] = 100;
		else
			motor[FrontSideways] = 0;
		if(joystick.joy1_TopHat == 0) {
			nMotorEncoder = 0;
			motor[LeftForward] = 100;
			while(nMotorEncoder != 1440);
			motor[LeftForward] = 0;
		}
		if(joystick.joy1_TopHat == 2) {
			nMotorEncoder = 0;
			motor[RightForward] = 100;
			while(nMotorEncoder != 1440);
			motor[RightForward] = 0;
		}
		if(joystick.joy1_TopHat == 4) {
			nMotorEncoder = 0;
			motor[BackSideways] = 100;
			while(nMotorEncoder != 1440);
			motor[BackSideways] = 0;
		}
		if(joystick.joy1_TopHat == 6) {
			nMotorEncoder = 0;
			motor[FrontSideways] = 100;
			while(nMotorEncoder != 1440);
			motor[FrontSideways] = 0;
		}
	}
}
