#pragma config(Hubs, S1, HTMotor, HTMotor, none, none)
#pragma config(Hubs, S2, HTMotor, HTServo, none, none)
#pragma config(Sensor, S3, IR, sensorHiTechnicIRSeeker1200)
#pragma config(Motor, mtr_S1_C1_1, LeftForward, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor, mtr_S1_C1_2, FrontSideways, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor, mtr_S1_C2_1, BackSideways, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor, mtr_S1_C2_2, RightForward, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor, mtr_S2_C1_1, ArmLeft, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor, mtr_S2_C1_2, ArmRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Servo, srvo_S2_C2_1, ArmServoLeft, tServoStandard)
#pragma config(Servo, srvo_S2_C2_2, ArmServoRight, tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define ENCODERSTOP 4096

bool motorLeftForward = false; //Says whether we are testing an encoder or not
bool motorRightForward = false;
bool motorBackSideways = false;
bool motorFrontSideways = false;

task main() {
	//Initialize
	motor[LeftForward] = motor[RightForward] = motor[BackSideways] = motor[FrontSideways] = motor[ArmLeft] = motor[ArmRight] = 0; //Turn off the motors
	nMotorEncoder[LeftForward] = nMotorEncoder[RightForward] = nMotorEncoder[BackSideways] = nMotorEncoder[FrontSideways] = nMotorEncoder[ArmLeft] = nMotorEncoder[ArmRight] = 0; //Might as well reset the encoders too
	servo[ArmServoLeft] = servo[ArmServoRight] = 0; //And set the servos
	waitForStart();
	while(true) {
		//Motors
		if(joy1Btn(1)) //If button 1 is pressed, start the motor
			motor[LeftForward] = 100;
		else if(!motorLeftForward) //If we aren't testing the encoder, stop the motor
			motor[LeftForward] = 0;
		if(joy1Btn(2))
			motor[RightForward] = 100;
		else if(!motorRightForward)
			motor[RightForward] = 0;
		if(joy1Btn(3))
			motor[BackSideways] = 100;
		else if(!motorBackSideways)
			motor[BackSideways] = 0;
		if(joy1Btn(4))
			motor[FrontSideways] = 100;
		else if(!motorFrontSideways)
			motor[FrontSideways] = 0;
		if(joystick.joy1_TopHat == 0) { //Start testing encoder if top D-Pad button is pressed
			nMotorEncoder[LeftForward] = 0; //Reset the encoder
			motor[LeftForward] = 100; //Go!
			motorLeftForward = true; //Now testing LeftForward
		}
		if(joystick.joy1_TopHat == 2) { //Right D-Pad button
			nMotorEncoder[RightForward] = 0;
			motor[RightForward] = 100;
			motorRightForward = true;
		}
		if(joystick.joy1_TopHat == 4) { //Bottom D-Pad button
			nMotorEncoder[BackSideways] = 0;
			motor[BackSideways] = 100;
			motorBackSideways = true;
		}
		if(joystick.joy1_TopHat == 6) { //Left D-Pad button
			nMotorEncoder[FrontSideways] = 0;
			motor[FrontSideways] = 100;
			motorFrontSideways = true;
		}
		if(motorLeftForward && nMotorEncoder[LeftForward] >= ENCODERSTOP) { //If we are testing encoder and time to stop, stop the motor
			motor[LeftForward] = 0;
			motorLeftForward = false;
		}
		if(motorRightForward && nMotorEncoder[RightForward] >= ENCODERSTOP) {
			motor[RightForward] = 0;
			motorRightForward = false;
		}
		if(motorBackSideways && nMotorEncoder[BackSideways] >= ENCODERSTOP) {
			motor[BackSideways] = 0;
			motorBackSideways = false;
		}
		if(motorFrontSideways && nMotorEncoder[FrontSideways] >= ENCODERSTOP) {
			motor[FrontSideways] = 0;
			motorFrontSideways = false;
		}
		//Arm
		if(joy1Btn(5)) { //If button 5 is pressed, start arm up
			if(nMotorEncoder[ArmRight] < ARMTOP) //Protects from operator forcing the arm above its highest point
				motor[ArmLeft] = motor[ArmRight] = 100;
			else
				motor[ArmLeft] = motor[ArmRight] = 0;
		}
		if(joy1Btn(7)) { //If button 7 is pressed, start arm down
			if(nMotorEncoder[ArmLeft] > -ARMTOP) //Protects from operator forcing the arm below its lowest point
				motor[ArmLeft] = motor[ArmRight] = -100;
			else
				motor[ArmLeft] = motor[ArmRight] = 0;
		}
		if(joy1Btn(6) && servoValue[ArmServoLeft] < 255 && servoValue[ArmServoRight] < 255) { //If button 6 is pressed and servos aren't at maximum, open hand
			servo[ArmServoLeft] += servoFactor; //Increase servo positions
			servo[ArmServoRight] += servoFactor;
		}
		if(joy1Btn(8) && servoValue[ArmServoLeft] > 0 && servoValue[ArmServoRight] > 0) { //If button 8 is pressed and servos aren't at minimum, close hand
			servo[ArmServoLeft] -= servoFactor; //Decrease servo positions
			servo[ArmServoRight] -= servoFactor;
		}
	}
}
