#pragma config(Hubs, S1, HTMotor, HTMotor, none, none)
#pragma config(Sensor, S1, , sensorI2CMuxController)
#pragma config(Motor, mtr_S1_C1_1, FrontLeft, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor, mtr_S1_C1_2, FrontRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor, mtr_S1_C2_1, BackLeft, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor, mtr_S1_C2_2, BackRight, tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "common.c"

//Constants
#include "constants.h"

//Initialize our globals
byte joystickScale = JOYSTICKHIGH; //Used to scale down robot movements
byte armScale = ARMHIGH; //Used to scale arm movements
byte armScaleDown = ARMDOWNHIGH; //Second scale for going down since the arm will be moving much faster
byte shoulderScale = SHOULDERHIGH; //Same for shoulder
byte shoulderScaleDown = SHOULDERDOWNHIGH;

bool forwardlock = true; //Used for direction locking
bool sidelock = true;

task joystickControl() { //Asynchronous task for joystick control
	while(true) {
		//Joystick 1 - Driver
	}
}

task armControl() { //Another asynchronous task to move the arm
	while(true) {
		//Joystick 2 - Operator
	}
}

task main() {
	//Initialize
	motor[] = 0; //Turn off the motors
	nMotorEncoder[] = 0; //Might as well reset the encoders too

	waitForStart();

	StartTask(joystickControl); //Go ahead and start critical joystick functions in their own task
	StartTask(armControl); //Start arm functions in their own task too
	while(true) {
		//Joystick 1 - Driver

		if(joy1Btn(6)) //If the driver is pressing button 6, scale down robot movements
			joystickScale = JOYSTICKLOW;
		else //Else leave at full speed
			joystickScale = JOYSTICKHIGH;

		if(joy1Btn(5)) //If the driver is pressing button 5, lock to y-axis movement
			sidelock = false;
		else
			sidelock = true;

		if(joy1Btn(7)) //If the driver is pressing button 7, lock to x-axis movement
			forwardlock = false;
		else
			forwardlock = true;
	}
}
